const premierLeagueChampionnats = [
    {
        nom: "Premier League",
        couleur: ["blue", "red", "green"],  // 🔵🔴🟢 Autres couleurs
        clubs: [
            { nom: "Man City", logo: "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg", points: 80 },
            { nom: "Arsenal", logo: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg", points: 77 },
            { nom: "Liverpool", logo: "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg", points: 75 }
        ]
    }
];